name: synapsis
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  battery_plus: ^4.0.2
  camera: ^0.10.5+3
  cool_alert: ^2.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.0.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  location: ^4.3.0
  sensors_plus: ^3.0.3
  slide_digital_clock: ^1.0.3
  syncfusion_flutter_charts: ^22.2.10
  flutter_barcode_scanner: ^2.0.0
  flutter_exif_rotation: ^0.5.1
  image: ^4.0.17
  google_maps_flutter: ^2.4.0
  qr_flutter: ^4.1.0
  package_info_plus: ^4.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
